travis:
  secure:
    BINSTAR_TOKEN: U92dRQCAuCqosA5PJAZ/SJWGhUDOvTUfR0u2lvBbePxvo2wEaN9l9w1Qo6m9PJtGJX6HqIaVHvKHDipfROsQ0YuloNDqohubOJncauG4KUzFUsrtF0e6yDmObev4GwWFH3j9Q94DfsNTqbG7tthXsarIs4ePULaMqscMC29/WZcMYLP5hEJXJqpuO1Nw7A+ZxvBzajJsmmNQQdmekeGIi6s+R7B/69SmVjgRHmtItfIccoMqEZlCoqZPPO6TQpiH1TU69ZiwJK5mCw3vGVS+4HS4R1NPXqDzSgm0Kc9rL57L+6drwsZgsKD+VK7JEqkCQxtJb/qcYKBGoK+e1GSpGHZDp5yrnVMirmn0d+FCISi4mn/851fDT36USPu0+kjqL4krXPhvslRn3bDkyiVVE0u5PlLHIr7dvQXxWSevedlOBnJlqXNXKRxdQomLG96hPYEWeZUWh+0HsdG9EB9CXAKCVhCA3wkZKqnWoeM8Q5vIaLHOtUQbOv2sVJ5kfc4HOAWnEzFW5ZksC+uvfa4uyi4OGvdNys/3HJi5c9J1b8rQ7D3mgHe6/uPNN32nPQSDY+9RGmT905gU0iqxbcpApA1SvEZyMQGmvYsobXPeeNEmiSHlDbmR69baFwQULd//Pw2yBjjzUc9DQLeR8hm6GJI9HO6PwwTTkgfx9i0Uz7g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
